wp_payflow.settings:
  type: config_object
  label: 'WP Payflow settings'
  mapping:
    partner:
      type: string
      label: 'Partner'
    vendor:
      type: string
      label: 'Vendor'
    user:
      type: string
      label: 'User'
    password:
      type: string
      label: 'Password'
